export const WORLD_UNIT_METERS = 1;

export const PLANET_CENTER = Object.freeze({
  x: 0,
  y: 0,
  z: 0,
});

export const PLANET_RADIUS_METERS = 300_000;
export const ATMOSPHERE_RADIUS_METERS = 315_000;
export const ATMOSPHERE_THICKNESS_METERS =
  ATMOSPHERE_RADIUS_METERS - PLANET_RADIUS_METERS;

export const CAMERA_START_ALTITUDE_METERS = 1_500;
export const CAMERA_NEAR_METERS = 0.5;
export const CAMERA_FAR_METERS = 2_400_000;

export const SURFACE_MODE_MAX_ALTITUDE_METERS = 30_000;
export const ORBIT_MODE_MIN_ALTITUDE_METERS = 80_000;
export const LOD0_MAX_ALTITUDE_METERS = 5_000;
export const LOD1_MAX_ALTITUDE_METERS = 20_000;
export const LOD2_MAX_ALTITUDE_METERS = 60_000;
export const LOD3_MAX_ALTITUDE_METERS = 140_000;

export const FLOATING_ORIGIN_REBASE_DISTANCE_METERS = 10_000;

export const TERRAIN_BASE_CHUNKS_PER_FACE = 128;
export const TYPE4_GLOBAL_CHUNKS_PER_FACE = 4;
export const TYPE4_GLOBAL_CHUNK_RESOLUTION = 8;

export const DEFAULT_MAX_ACTIVE_CHUNKS = 280;
export const MIN_ACTIVE_CHUNKS = 96;
export const DEFAULT_MAX_CHUNK_GENERATIONS_PER_FRAME = 5;
export const MIN_CHUNK_GENERATIONS_PER_FRAME = 2;
export const DEFAULT_CHUNK_RESOLUTION = 56;
export const MIN_CHUNK_RESOLUTION = 20;
export const DEFAULT_MAX_GENERATION_QUEUE_LENGTH = 360;
export const DEFAULT_MAX_CHUNK_GENERATION_TIME_MS = 5;
export const MIN_CHUNK_GENERATION_TIME_MS = 2;
export const DEFAULT_MAX_CACHED_CHUNKS = 64;
export const MIN_CACHED_CHUNKS = 24;
export const CHUNK_STREAM_UPDATE_INTERVAL_MS = 150;
export const CHUNK_STREAM_PREDICTION_SECONDS = 4;
export const CHUNK_PRELOAD_RADIUS_MULTIPLIER = 1.35;
export const CHUNK_UNLOAD_RADIUS_MULTIPLIER = 1.75;
export const CHUNK_CACHE_MAX_AGE_MS = 20_000;
export const RENDER_SURFACE_CHUNK_MESHES = false;
export const SMOOTH_SURFACE_LOGICAL_ACTIVE_CHUNK_LIMIT = 96;
export const SMOOTH_SURFACE_CRITICAL_CHUNK_RADIUS = 4;
export const SMOOTH_SURFACE_GENERATION_QUEUE_LIMIT = 180;

export const MIN_RENDER_SCALE = 0.58;
export const MAX_RENDER_SCALE = 1.15;
export const DEFAULT_RENDER_SCALE = 1;
export const DESKTOP_PIXEL_RATIO_CAP = 2;
export const MOBILE_PIXEL_RATIO_CAP = 1.5;

export const STAR_FIELD_RADIUS_METERS = 900_000;
export const SUN_LIGHT_POSITION_METERS = Object.freeze({
  x: 220_000,
  y: 180_000,
  z: 90_000,
});

export const CAMERA_GROUND_SPEED_ALTITUDE_METERS = 1_000;
export const CAMERA_LOW_ATMOSPHERE_SPEED_ALTITUDE_METERS = 20_000;
export const CAMERA_HIGH_ATMOSPHERE_SPEED_ALTITUDE_METERS = 100_000;
export const CAMERA_MIN_SPEED_MPS = 10;
export const CAMERA_SURFACE_SPEED_MPS = 100;
export const CAMERA_LOW_ATMOSPHERE_SPEED_MPS = 1_000;
export const CAMERA_HIGH_ATMOSPHERE_SPEED_MPS = 10_000;
export const CAMERA_SPACE_SPEED_ALTITUDE_FACTOR = 0.25;
export const CAMERA_MAX_SPACE_SPEED_MPS = 180_000;

export type WorldMode = "surface" | "transition" | "orbit";
